services:
  api:
    build:
      context: .
      dockerfile: RentNRide.Api/Dockerfile
    image: rentnride-api:1.0
    container_name: rentnride-api
    restart: always
    ports:
      - "${API_PORT}:8080"
    environment:
      - POSTGRESQL_HOST=${POSTGRESQL_HOST}
      - POSTGRESQL_PORT=${POSTGRESQL_PORT}
      - POSTGRESQL_DB=${POSTGRESQL_DB}
      - POSTGRESQL_USER=${POSTGRESQL_USER}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - MINIO_HOST=${MINIO_HOST}
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_USER=${MINIO_USER}
      - MINIO_PASSWORD=${MINIO_PASSWORD}
    depends_on:
      - database-updater
      - rabbitmq
      - minio

  database-updater:
    build:
      context: .
      dockerfile: RentNRide.Deployment.Database/Dockerfile
    image: rentnride-dbup:1.0
    container_name: rentnride-database-updater
    restart: "no"
    environment:
      - POSTGRESQL_HOST=${POSTGRESQL_HOST}
      - POSTGRESQL_PORT=${POSTGRESQL_PORT}
      - POSTGRESQL_DB=${POSTGRESQL_DB}
      - POSTGRESQL_USER=${POSTGRESQL_USER}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
    depends_on:
      - postgresql

  postgresql:
      image: postgres:15
      container_name: postgresql_db
      restart: always
      environment:
        - POSTGRES_DB=${POSTGRESQL_DB}
        - POSTGRES_USER=${POSTGRESQL_USER}
        - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      ports:
        - "5432:5432"
      volumes:
        - postgresql_data:/var/lib/postgresql/data
        - ./RentNRide.Deployment.Database/Scripts:/docker-entrypoint-initdb.d

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_broker
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"

  minio:
    image: minio/minio
    container_name: minio_storage
    restart: always
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  postgresql_data:
  minio_data:
